export const PROJECTS = [
  {
    id: 1,
    title: "AI-Assisted Brain Computer Interface for EEG-to-Text Communication",
    description:
      "A real-time BCI system using the Neurosity Crown headset to translate multi-channel EEG signals into text commands through artifact removal, filtering, FFT feature extraction, and classification with optimized KNN and Random Forest models. Features a TypeScript React dashboard built with Vite to display outputs like Yes, No, Help, and Water, integrating signal processing, machine learning, and frontend development for non-invasive communication.",
    technologies: [
      "Neurosity Crown",
      "EEG",
      "FFT",
      "KNN",
      "Random Forest",
      "TypeScript",
      "Vite",
      "React",
      "JavaScript",
    ],
    image: "/eeg-bci-interface-dashboard.jpg",
    github: "#",
    demo: "#",
  },
  {
    id: 2,
    title: "Air Quality Monitoring System",
    description:
      "A real-time system utilizing the MQ-135 gas sensor and Arduino Uno to measure environmental pollutants, compute the Air Quality Index (AQI), and deliver visual LED alerts and auditory buzzer warnings when thresholds are exceeded, demonstrating skills in sensor integration, data acquisition, and automated monitoring.",
    technologies: [
      "MQ-135",
      "Arduino Uno",
      "LED Display",
      "Buzzer",
      "AQI Calculation",
    ],
    image: "/air-quality-monitoring-system.jpg",
    github: "#",
    demo: "#",
  },
  {
    id: 3,
    title: "Line Following Robot Using L293D",
    description:
      "Designed and built a line-following robot incorporating the L293D motor driver, BO motors, IR proximity sensors, and a custom Vero board circuit, with precise motor control, 9V power supply, modular pin headers, optimized wiring, stable wheels, and a manual switch for operation, showcasing skills in embedded design, component integration, and sensor-driven robotic control.",
    technologies: [
      "L293D",
      "BO Motors",
      "IR Proximity Sensors",
      "Vero Board",
      "Embedded Circuit Design",
    ],
    image: "/line-following-robot.jpeg",
    github: "#",
    demo: "#",
  },
  {
    id: 4,
    title: "Real-Time Data Logging System Using ESP32",
    description:
      "Designed and implemented a system with ESP32 to capture analog and digital sensor inputs, logging data to Google Sheets every 10 seconds, incorporating circuit design and API integration for automated acquisition and remote monitoring.",
    technologies: [
      "ESP32",
      "Google Sheets",
      "API",
      "Sensor Inputs",
      "Circuit Design",
    ],
    image: "/real-time-data-logging-system.jpg",
    github: "#",
    demo: "#",
  },
  {
    id: 5,
    title: "Image Enhancement Using Interpolation Techniques",
    description:
      "A project applying interpolation methods to boost image quality and resolution, enhancing visual fidelity by filling pixel gaps with strategic techniques while preserving original features.",
    technologies: ["Interpolation Techniques", "Image Processing"],
    image: "/image-enhancement-interpolation.png",
    github: "#",
    demo: "#",
  },
  {
    id: 6,
    title: "Smart Home Automation System Using ESP8266 & ESP32",
    description:
      "Designed and implemented a comprehensive smart home system with ESP32 as the central controller and ESP8266 modules for specific devices, enabling Wi-Fi-based automation and remote control of lighting, heating, security, and door locks.",
    technologies: [
      "ESP8266",
      "ESP32",
      "Wi-Fi Communication",
      "Smart Home Automation",
    ],
    image: "/smart-home-automation-system.png",
    github: "#",
    demo: "#",
  },
  {
    id: 7,
    title: "Design of a Controller for Third- or Higher-Order Systems",
    description:
      "Designed and implemented controllers for third- and higher-order dynamic systems, emphasizing stability, transient response optimization, and meeting performance specifications through classical and modern control techniques.",
    technologies: [
      "Control Systems",
      "Stability Analysis",
      "Transient Response Optimization",
      "Classical Control",
      "Modern Control",
    ],
    image: "/controller-design-systems.png",
    github: "#",
    demo: "#",
  },
  {
    id: 8,
    title: "Paper Weight Fabrication Project",
    description:
      "Fabricated a paper weight from a raw material rod, showcasing engineering workshop skills in precision machining through processes like cutting, filing, reaming, threading, drilling, lathe shaping and finishing, and engraving for detailed markings and polish, emphasizing material selection, manual and machine-based techniques, and craftsmanship in creating a functional, refined product.",
    technologies: [
      "Lathe Machine",
      "Engraving Machine",
      "Cutting",
      "Filing",
      "Reaming",
      "Threading",
      "Drilling",
      "Precision Machining",
    ],
    image: "/paper-weight-fabrication.jpg",
    github: "#",
    demo: "#",
  },
];
